# Generated by Django 3.2.12 on 2023-02-10 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='useropt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.category')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.options')),
                ('uqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.questions')),
            ],
        ),
        migrations.CreateModel(
            name='testtaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tper', models.FloatField()),
                ('tdate', models.DateField(auto_now_add=True)),
                ('tcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.category')),
                ('tuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.questions'),
        ),
        migrations.CreateModel(
            name='correctopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.options')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.questions')),
            ],
        ),
    ]
